const AboutData = [
  {
    id: 0,
    name: "HONG_DEV",
    img: "Hong.jpg",
    position: "Back-end",
    git: "https://github.com/hong-dev",
    insta: "https://www.instagram.com/hong._.dev",
    color: "red",
  },
  {
    id: 1,
    name: "CARMIN",
    img: "Carmin.jpg",
    position: "Front-end",
    git: "https://github.com/carminchameleon",
    insta: "https://instagram.com/hwanggee20",
    color: "orange",
  },
  {
    id: 2,
    name: "SUNNY",
    img: "Sunny.jpg",
    position: "Front-end",
    git: "https://github.com/sunghaeJoung",
    insta: "https://instagram.com/_sunghae__",
    color: "yellow",
  },
  {
    id: 3,
    name: "WHYBEIN",
    img: "Whybein.jpg",
    position: "Back-end",
    git: "https://github.com/whybein",
    insta: "https://instagram.com/whybein",
    color: "green",
  },
  {
    id: 4,
    name: "SOL",
    img: "Sol.jpg",
    position: "Front-end",
    git: "https://github.com/Wanderlust-sol",
    insta: "https://instagram.com/wanderlust_sol",
    color: "blue",
  },
  {
    id: 5,
    name: "AIDEN",
    img: "Aiden.jpg",
    position: "Front-end",
    git: "https://github.com/ki-hyeonkwon",
    insta: "https://www.instagram.com/1hr_1min/?hl=ko",
    color: "navy",
  },
  {
    id: 6,
    name: "KAY",
    img: "Kay.jpg",
    position: "Back-end",
    git: "https://github.com/k904808",
    insta: "https://www.instagram.com/kaaaaaaay_yoo/",
    color: "purple",
  },
];

export default AboutData;
